name: Mock Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - day3-changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print branch
        run: echo "Running fake pipeline on $GITHUB_REF"
      - name: Generate noise
        run: |
          node -e "console.log('Pretend build complete')"
